services:
  full:
    build:
      context: .
      dockerfile: Dockerfile
    image: lexiniana-full:latest
    container_name: lexiniana-full
    volumes:
      - ./:/workspace
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: 32G
    profiles: ["full"]
